name: Ejecutar código Python

on:
  push:
    branches:
      - main  # Cambia "main" por la rama principal de tu repositorio si es diferente

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2
    
    - name: Configurar entorno Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Reemplaza "3.x" por la versión de Python que necesites
    
    #- name: Instalar dependencias
    #  run: pip install -r requirements.txt  # Si tienes un archivo requirements.txt, de lo contrario, omite esta línea
    
    - name: Ejecutar código Python
      run: python main.py  # Reemplaza "tu_archivo.py" con el nombre de tu archivo Python

